name: CI/CD - Testing

on:
  push:
    branches:
      - test/pipeline
    paths:
      - Dockerfile
      - .github/workflows/ci-test.yml
    
env:
  AWS_REGION:    ap-southeast-3
  NAMESPACE:     shopnow
  EKS_CLUSTER:   shopnow-prod-eks
  IMAGE_VERSION: ${{ secrets.ECR_REGISTRY }}/${{ github.event.repository.name }}:test_${{ github.sha }}
  HELM_RELEASE:  ${{ github.event.repository.name }}

  SNYKSCAN_SAST_REPORT:   "snyk_sast_test_${{ github.event.repository.name }}_${{ github.sha }}"
  SNYKSCAN_SCA_REPORT:    "snyk_sca_test_${{ github.event.repository.name }}_${{ github.sha }}"
  TRIVYFS_REPORT:         "trivy_fs_test_${{ github.event.repository.name }}_${{ github.sha }}"
  TRIVY_IMAGE_REPORT:     "trivy_img_test_${{ github.event.repository.name }}_${{ github.sha }}"
  ARACHNI_WEBSITE_REPORT: "arachni_test_${{ github.event.repository.name }}_${{ github.sha }}"
  ZAP_REPORT:             "zap_test_${{ github.event.repository.name }}_${{ github.sha }}"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  snyk-sast:
    name: Snyk Source Code Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Node Modules for Snyk
        uses: actions/cache@v4
        with:
          path: .npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run Snyk scan
        run: |
          if ! docker run --rm \
            --entrypoint /bin/sh \
            -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
            -v $(pwd):/app -w /app \
            snyk/snyk:node -c "
              npm ci --cache /app/.npm --prefer-offline --no-audit --ignore-scripts
              snyk code test --severity-threshold=high --json > snyk_sast_result.json
              SNYK_EXIT_CODE=\$?
              npm install -g snyk-to-html
              snyk-to-html -i snyk_sast_result.json -o ${{ env.SNYKSCAN_SAST_REPORT }}.html || true
              exit \$SNYK_EXIT_CODE
            "; then
            echo "::error title=Snyk SAST Scan Failed:: Found issues with 'HIGH/CRITICAL' severity"
          fi

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-sast-report
          path: ${{ env.SNYKSCAN_SAST_REPORT }}.html
          retention-days: 5

  snyk-sca:
    name: Snyk SCA Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Node Modules for Snyk
        uses: actions/cache@v4
        with:
          path: .npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run Snyk scan
        run: |
          if ! docker run --rm \
            --entrypoint /bin/sh \
            -e SNYK_TOKEN=${{ secrets.SNYK_TOKEN }} \
            -v $(pwd):/app -w /app \
            snyk/snyk:node -c "
              npm ci --cache /app/.npm --prefer-offline --no-audit --ignore-scripts
              snyk test --severity-threshold=high --all-projects --json > snyk_sca_result.json
              SNYK_EXIT_CODE=\$?
              npm install -g snyk-to-html
              snyk-to-html -i snyk_sca_result.json -o ${{ env.SNYKSCAN_SCA_REPORT }}.html || true
              exit \$SNYK_EXIT_CODE
            "; then
            echo "::error title=Snyk SCA Scan Failed:: Found issues with 'HIGH/CRITICAL' severity"
          fi

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snyk-sca-report
          path: ${{ env.SNYKSCAN_SCA_REPORT }}.html
          retention-days: 5

  trivy-fs-scan:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy FS scan
        run: |
          if ! docker run --rm \
            -v $PWD:/${{ github.event.repository.name }} \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:0.69.3 fs /${{ github.event.repository.name }} \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            --no-progress \
            --format template \
            --template "@contrib/html.tpl" \
            --output /${{ github.event.repository.name }}/${{ env.TRIVYFS_REPORT }}.html; then
            echo "::error title=Trivy Scan Failed:: (HIGH/CRITICAL)"
          fi
          
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-fs-report
          path: ${{ env.TRIVYFS_REPORT }}.html
          retention-days: 5

  notify-request-approval:
    name: Send Approval Request to Telegram
    runs-on: ubuntu-latest

    steps:
      - name: Send Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            [WAITING APPROVAL] 
            All source code security scans have PASSED!
            The pipeline is now waiting for your approval to build and push the image to ECR.
            
            Triggered by: ${{ github.actor }}
            Branch: ${{ github.ref_name }}
            Click here to Approve: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  build:
    name: Build and Push ECR
    runs-on: ubuntu-latest
    environment: testing
    needs: notify-request-approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ACCESS_PROD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          network: host
          build-args: |
            REACT_APP_BASE_API_URL=${{ secrets.REACT_APP_BASE_API_URL }}
          tags: ${{ env.IMAGE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  trivy-image-scan:
    name: Trivy Image Scan
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ACCESS_PROD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR and pull image
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
          docker pull ${{ env.IMAGE_VERSION }}

      - name: Scan image
        run: |
          docker run --rm \
            -v $(pwd):/output \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:0.69.3 image \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            --no-progress \
            --format template \
            --template "@contrib/html.tpl" \
            --output /output/${{ env.TRIVY_IMAGE_REPORT }}.html \
            ${{ env.IMAGE_VERSION }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-image-report
          path: ${{ env.TRIVY_IMAGE_REPORT }}.html
          retention-days: 5

  notify:
    name: Notify Telegram
    runs-on: ubuntu-latest
    needs: [build, snyk-sast, snyk-sca, trivy-fs-scan, trivy-image-scan]
    if: always()
    steps:
      - name: Determine failed jobs
        id: check_status
        run: |
          FAILED_JOBS=""
          if [ "${{ needs.snyk-sast.result }}" == "failure" ]; then FAILED_JOBS="$FAILED_JOBS snyk-sast"; fi
          if [ "${{ needs.snyk-sca.result }}" == "failure" ]; then FAILED_JOBS="$FAILED_JOBS snyk-sca"; fi
          if [ "${{ needs.trivy-fs-scan.result }}" == "failure" ]; then FAILED_JOBS="$FAILED_JOBS trivy-fs-scan"; fi
          if [ "${{ needs.trivy-image-scan.result }}" == "failure" ]; then FAILED_JOBS="$FAILED_JOBS trivy-image-scan"; fi
          echo "failed_jobs=$FAILED_JOBS" >> $GITHUB_OUTPUT

      - name: Download only failed reports
        if: steps.check_status.outputs.failed_jobs != ''
        uses: actions/download-artifact@v4
        with:
          pattern: '*-report'
          path: reports
          merge-multiple: true

      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Status: ${{ contains(needs.*.result, 'failure') && 'FAILED' || 'PASSED' }}
              Failed Jobs: ${{ steps.check_status.outputs.failed_jobs }}
              Pipeline: ${{ github.workflow }}
              Branch: ${{ github.ref_name }}
              Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Send HTML Reports to Telegram
        if: steps.check_status.outputs.failed_jobs != ''
        run: |
          for job in ${{ steps.check_status.outputs.failed_jobs }}; do
            # Map job name to its specific artifact filename pattern using exact prefixes
            case $job in
              snyk-sast) FILE_PATTERN="snyk_sast_test*" ;;
              snyk-sca) FILE_PATTERN="snyk_sca_test*" ;;
              trivy-fs-scan) FILE_PATTERN="trivy_fs_test*" ;;
              trivy-image-scan) FILE_PATTERN="trivy_img_test*" ;;
            esac
            
            # Send the specific file found
            for file in reports/$FILE_PATTERN.html; do
              if [ -f "$file" ]; then
                curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument" \
                  -F chat_id="${{ secrets.TELEGRAM_TO }}" \
                  -F document="@$file" \
                  -F caption="Security alert: $job failed. Report attached."
              fi
            done
          done